<?php

/**
 * Tag Multi Site
 *
 * GuilhermeVenerato_TagMultiSite
 *
 * @category  GuilhermeVenerato
 * @package   GuilhermeVenerato_TagMultiSite
 * @author    Guilherme Venerato <guilhermevenerato@hotmail.com>
 * @copyright Copyright (c) 2022 Guilherme Venerato
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \GuilhermeVenerato\TagMultiSite\Block\Data $block */

echo $block->getTagMultiSite();
